apiVersion: v1
kind: Secret
metadata:
  name: tasky-env
  namespace: tasky
type: Opaque
stringData:
  # Connection string for your MongoDB VM (with auth)
  MONGODB_URI: "mongodb://tasky_user:TaskyPa55!@10.50.2.216:27017/tasky?authSource=admin"
  # Secret key used by your Go app for signing JWTs
  SECRET_KEY:   "secret123"

