apiVersion: v1
kind: Secret
metadata:
  name: tasky-env
  namespace: tasky
type: Opaque
stringData:
  MONGODB_URI: "mongodb://tasky_user:TaskyPa55!@54.208.117.245:27017/tasky?authSource=admin"
  SECRET_KEY:   "secret123"
